### ISSUE TITLE
Problem in UserTrust

### ISSUE THREAD

**Issue by MisterXYCB** [MiraculixxT/GHG-Bot#1]
# Stärkere Gewichtung durch schlechte Votes
Wenn ein User genügend Trust verliert, um auf das Level "-2" oder niedriger zu fallen, wird sein Vote mit einer Gewichtung von 2.5 berechnet, so wie es für das Level "5" oder höher vorgesehen ist.

**Comment by MiraculixxT** [comment]
Du hast Recht, vielen Dank für das Melden des Bugs. Keine Ahnung was ich mir dabei gedacht habe...
